###服务的端口号
server:
  port: 8100
eureka:
  instance:
    ###注册中心IP地址
    homename: 127.0.0.1
  client:
    service-url:
      ###注册地址
      defaultZone: http://${eureka.instance.homename}:${server.port}/eureka/
    ### 因为自己是注册中心，是否需要将自己注册给自己的注册中心  集群的时候是true
    register-with-eureka: false
    ### 因为自己是注册中心，不需要去检索服务信息
    fetch-registry: false
  server:
    #测试的时候关闭自我保护机制，保证不可用服务及时不用
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
